name: wc_flutter_share
description: A Flutter plugin for sharing file, text and subject at the same time with other applications.
version: 0.2.2
homepage: https://github.com/aarajput/wc_flutter_share

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.6.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.wisecrab.wc_flutter_share
        pluginClass: WcFlutterSharePlugin
      ios:
        pluginClass: WcFlutterSharePlugin
